// <auto-generated />
using System;
using APIV22.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace APIV22.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250510000908_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("APIV22.Models.ZapatillaPersonalizada", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ColorCordones")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorPlantilla")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorSuela")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ColorSuperior")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Estilo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NombreImagen")
                        .HasColumnType("text");

                    b.Property<string>("Suela")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("Talla")
                        .HasColumnType("integer");

                    b.Property<string>("Texto")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("ZapatillasPersonalizadas");
                });
#pragma warning restore 612, 618
        }
    }
}
